#pragma once
#include"SDL.h"


#define KEY_UP SDL_SCANCODE_W
#define KEY_DOWN SDL_SCANCODE_S
#define KEY_LEFT SDL_SCANCODE_A
#define KEY_RIGHT SDL_SCANCODE_D

#define KEY_YES SDL_SCANCODE_J
#define KEY_NO SDL_SCANCODE_K

#define KEY_SEARCH SDL_SCANCODE_Q

#define KEY_JUMP SDL_SCANCODE_SPACE

#define KEY_DEBUG SDL_SCANCODE_P